"""Daily credit summary ledger API."""

from datetime import date

from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import Response
from sqlalchemy.orm import Session

from app.api.deps import CurrentUser, require_any_permission
from app.config.settings import settings
from app.database.business_session import get_business_db
from app.reports.gl_ledger_credit_summary_pdf import render_gl_ledger_credit_summary_pdf
from app.schemas.gl_ledger_credit_summary import GlLedgerCreditSummaryData, GlLedgerCreditSummaryRequest
from app.schemas.gl_ledger_report import (
    GlAccountLookup,
    GlLedgerEmailRequest,
    GlLedgerEmailResponse,
    GlLedgerEmailStatus,
)
from app.services.email_service import EmailDeliveryError, EmailNotConfiguredError, EmailService
from app.services.gl_ledger_credit_summary_service import GlLedgerCreditSummaryService
from app.services.gl_ledger_report_service import GlLedgerReportService

router = APIRouter()

_VIEW_PERMS = require_any_permission(
    "reports.gl_ledger.view",
    "inventory.fin_item.view",
    "auth.admin.full",
)


def _build_pdf(params: GlLedgerCreditSummaryRequest, db: Session) -> tuple[bytes, str, GlLedgerCreditSummaryData]:
    report = GlLedgerCreditSummaryService(db).build_report(params)
    pdf_bytes = render_gl_ledger_credit_summary_pdf(report)
    filename = f"gl-ledger-credit-{params.date_from}-{params.date_to}.pdf"
    return pdf_bytes, filename, report


def _pdf_response(params: GlLedgerCreditSummaryRequest, *, inline: bool, db: Session) -> Response:
    pdf_bytes, filename, _report = _build_pdf(params, db)
    disposition = "inline" if inline else "attachment"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'{disposition}; filename="{filename}"'},
    )


@router.get("/accounts/search", response_model=list[GlAccountLookup])
def search_accounts(
    q: str = Query(..., min_length=1),
    _user: CurrentUser = Depends(_VIEW_PERMS),
    db: Session = Depends(get_business_db),
):
    return GlLedgerReportService(db).search_accounts(q)


@router.get("/accounts/{ac_id}", response_model=GlAccountLookup)
def get_account(
    ac_id: int,
    _user: CurrentUser = Depends(_VIEW_PERMS),
    db: Session = Depends(get_business_db),
):
    return GlLedgerReportService(db).lookup_account(ac_id)


@router.get("/pdf")
def generate_pdf_get(
    start_ac_id: int = Query(..., ge=1),
    end_ac_id: int = Query(..., ge=1),
    date_from: date = Query(...),
    date_to: date = Query(...),
    suppress_zero_bal: bool = Query(False),
    complete_report: bool = Query(False),
    page_wise: bool = Query(False),
    inline: bool = Query(True),
    _user: CurrentUser = Depends(_VIEW_PERMS),
    db: Session = Depends(get_business_db),
):
    params = GlLedgerCreditSummaryRequest(
        start_ac_id=start_ac_id,
        end_ac_id=end_ac_id,
        date_from=date_from,
        date_to=date_to,
        suppress_zero_bal=suppress_zero_bal,
        complete_report=complete_report,
        page_wise=page_wise,
    )
    return _pdf_response(params, inline=inline, db=db)


@router.post("/pdf")
def generate_pdf(
    params: GlLedgerCreditSummaryRequest,
    inline: bool = Query(False),
    _user: CurrentUser = Depends(_VIEW_PERMS),
    db: Session = Depends(get_business_db),
):
    return _pdf_response(params, inline=inline, db=db)


@router.post("/email", response_model=GlLedgerEmailResponse)
def email_pdf(
    params: GlLedgerEmailRequest,
    current_user: CurrentUser = Depends(_VIEW_PERMS),
    db: Session = Depends(get_business_db),
):
    try:
        pdf_bytes, filename, report = _build_pdf(params, db)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Could not generate report PDF: {exc}",
        ) from exc

    recipients = [part.strip() for part in params.to_email.split(",") if part.strip()]
    subject = params.subject or (
        f"GL Credit Summary {params.date_from.strftime('%d/%m/%Y')} - "
        f"{params.date_to.strftime('%d/%m/%Y')}"
    )
    body_lines = [
        "Please find the daily credit summary ledger attached.",
        "",
        f"Company: {report.company_name}",
        f"Criteria: {report.criteria}",
        f"Accounts listed: {report.total_accounts}",
        f"Generated by: {current_user.username}",
        f"Generated on: {report.printed_on}",
    ]
    if params.message:
        body_lines.extend(["", "Message:", params.message])
    body_lines.extend(["", f"This is an automated message from {settings.app_name}."])

    email_service = EmailService()
    try:
        email_service.send_email(
            recipients,
            subject,
            "\n".join(body_lines),
            attachment=(filename, pdf_bytes, "application/pdf"),
        )
    except EmailNotConfiguredError as exc:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=str(exc)) from exc
    except EmailDeliveryError as exc:
        raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=str(exc)) from exc

    return GlLedgerEmailResponse(
        message=f"Report emailed to {', '.join(recipients)}.",
        recipients=recipients,
    )


@router.get("/email/status", response_model=GlLedgerEmailStatus)
def email_status(_user: CurrentUser = Depends(_VIEW_PERMS)):
    service = EmailService()
    from_email = settings.smtp_from_email.strip() or settings.smtp_user.strip()
    return GlLedgerEmailStatus(
        configured=service.is_configured(),
        from_email=from_email,
        hint=service.configuration_hint(),
    )
